services:
  - type: web
    name: face-emotion-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
pythonVersion: "3.12.13"  # or 3.11.x


